Numpy is a library in python that is used to represent and work with large and multidimensional array.

Inorder to import numpy library following syntax is used:



In [2]:
import numpy as np

arrays are created with numpy using following syntax:

In [3]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

# Vecorized Operations

In [4]:
a +2 # any mathematical operations done to array applies to all of its elements

array([3, 4, 5, 6, 7, 8])

In [5]:
b = a **2
b

array([ 1,  4,  9, 16, 25, 36])

In [6]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [7]:
a-10

array([-9, -8, -7, -6, -5, -4])

Vecorized operations does not change the value of the arrary unless you save the results under new variable

In [8]:
a ==5

array([False, False, False, False,  True, False])

In [9]:
a>1

array([False,  True,  True,  True,  True,  True])

In [10]:
a <9

array([ True,  True,  True,  True,  True,  True])

## Indexing & Slicing



In [11]:
want_these = [True, False, True, False, False , True] # boolean indexing
a[want_these]

array([1, 3, 6])

In [12]:
a[:3] # integer indexing

array([1, 2, 3])

Indexing using the [start:stop:step]

In [13]:
a[1:5:2] # here the indexing begins at index number 1, goes all the way up to index number 5(exclusive) and jumps
# by 2

array([2, 4])

In [14]:
a[[1,2,3]] # integer indexing by giving a list of integers 

array([2, 3, 4])

In [21]:
a[::-1]

array([6, 5, 4, 3, 2, 1])

basic sicing syntax is start:stop:step

:: is basically following the same concept of indexing as start:stop:step. Indexing just by :: defaults to all the elements in the array be selected and the step is defaulted to 1

:i: means index from 0 to i by stepping 1(the default value for step)

::i means index from 0 to the last index by stepping i

if i is negative, then indexing starts from the highest index value towards the lowest index value, and steps by i going backwards

In [18]:
a[::-2]

array([6, 4, 2])

In [17]:
a[::]

array([1, 2, 3, 4, 5, 6])

In [16]:
a[:5:]

array([1, 2, 3, 4, 5])

In [22]:
a[1:5]

array([2, 3, 4, 5])

In [15]:
a[a<4] # checks every element of the array to see if its less than 4 and creates a list of booean values then
#indexing takes place

array([1, 2, 3])

In [30]:
want_this = a<4

In [32]:
a[want_this]

array([1, 2, 3])

In [35]:
np.random.seed(101)
a = np.random.randint(0,100,1000)
a.shape # get how many elements in the array?

(1000,)

In [37]:
a[a>70].shape # get the count of numbers that are greater than 70

(289,)

In [40]:
(a>70).sum() # what happened here is that the numpy added all the true values as 1 and gave the result 
                # basically another way of getting the count

289

In [44]:
a[a%2==1].sum() # way of getting sum of all the odds in the array

24972

In [50]:
(a[(a >= 30) & (a <= 80)] ** 2).max() # getting all the number between 30 and 80 inclusive, squring them, and getting the highest number

6400